
# Model hyperparameters
learning_rate: 0.001
batch_size: 32
num_epochs: 10

# Dataset parameters
dataset:
  path: /path/to/dataset
  num_classes: 10
  img_height: 224
  img_width: 224
  train_split: 0.8

# Model architecture
model:
  name: resnet50
  pretrained: true
  num_classes: 10

# Optimization parameters
optimizer:
  name: adam
  weight_decay: 0.0001

# Scheduler parameters
scheduler:
  name: StepLR
  step_size: 5
  gamma: 0.1 